DEVICE_PATH := device/sts/a04br3
VENDOR_PATH := vendor/sts/a04br3
BOARD_VENDOR := sts
BOARD_DEVICE := a04br3
TARGET_DEVICE := a04br3
BUILD_BROKEN_DUP_RULES := true
BOARD_NO_RECOVERY_PATCH := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
ALLOW_MISSING_DEPENDENCIES := true
#RECOVERY_VARIANT := twrp
#T ARGET_RELEASETOOLS_EXTENSIONS := $(DEVICE_PATH)
TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/config.fs
TARGET_OTA_ASSERT_DEVICE := TAB-A04-BR3,a04br3
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_HAVE_WIFI := true
TARGET_SPECIFIC_HEADER_PATH := $(DEVICE_PATH)/include


WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_P2P:=P2P

#qcomが混ざる為無効
BOARD_USES_QCOM_HARDWARE := false
BOARD_USES_QTI_HARDWARE := false

#mtk！
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
TARGET_SOC := mt8167
TARGET_BOARD_PLATFORM := mt8167
TARGET_BOARD_PLATFORM_GPU := rogue_ge8300
MTK_HWC_VERSION := 1.4.0
MTK_GPU_VERSION := rgx clark 1.7ED
OVERRIDE_RS_DRIVER := libRSDriver.so

#disable
BOARD_GPS_LIBRARIES := false
BOARD_PROVIDES_LIBRIL := false
BOARD_PROVIDES_RILD := false
BOARD_HAS_GPS := false
BOARD_HAS_NFC := false
BOARD_HAS_RADIO := false
BOARD_HAS_HDMI := false
BOARD_SUPPORTS_SOUND_TRIGGER := false
WITHOUT_CHECK_API := true
MALLOC_SVELTE := true
# TARGET_LOW_RAM_DEVICE := true

#カメラを無効
USE_CAMERA_STUB := false
CAMERA_DAEMON_NOT_PRESENT := true
BOARD_HAS_CAMERA := false

# key
TARGET_PROVIDES_KEYMASTER := false
BOARD_USE_SOFT_GATEKEEPER := true

#artエラーの為追加
WITH_DEXPREOPT := true
#DISABLE_DEXPREOPT := true
#DONT_DEXPREOPT_PREBUILTS := true
#DEX_PREOPT_DEFAULT := nostripping
USE_DEX2OAT_DEBUG := false
#PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := --compiler-filter=verify
#PRODUCT_DEX_PREOPT_BOOT_FLAGS := --compiler-filter=verify
#PRODUCT_DEX_PREOPT_BOOT_FLAGS := --compiler-filter=verify-profile
#PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := --compiler-filter=speed-profile

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true
TARGET_IS_64_BIT := true
TARGET_BUILD_64BIT := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_USES_64_BIT_BINDER := true
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_BUILD_VARIANT := userdebug
TARGET_CPU_CORTEX_A53 := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_MEMCPY_OPT_DISABLE := true

#oat
DEX2OAT_TARGET_ARCH := arm64
DEX2OAT_TARGET_CPU_VARIANT := cortex-a53
DEX2OAT_TARGET_CPU_VARIANT_RUNTIME := default
DEX2OAT_TARGET_INSTRUCTION_SET_FEATURES := default

#DEX2OAT_IMAGE_XMS := 
#DEX2OAT_IMAGE_XMX :=
#DEX2OAT_XMS :=
#DEX2OAT_XMX :=

#ota
TARGET_OTA_ASSERT_DEVICE := TAB-A04-BR3,a04br3
AB_OTA_UPDATER := false

#test
BOARD_SUPPRESS_SECURE_ERASE := true
DISABLE_ASHMEM_TRACKING := true
BOARD_GLOBAL_CFLAGS += -DDISABLE_ASHMEM_TRACKING
BOARD_NO_SECURE_DISCARD := true
TARGET_NO_SENSOR_PERMISSION_CHECK := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/BOOT/BOOT/boot/boot_mode
BACKLIGHT_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
BOARD_RED_LED_PATH := "/sys/devices/platform/leds-mt65xx/leds/red"
BOARD_GREEN_LED_PATH := "/sys/devices/platform/leds-mt65xx/leds/green"
BOARD_BLUE_LED_PATH := "/sys/devices/platform/leds-mt65xx/leds/blue"

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a04br3
TARGET_NO_FACTORYIMAGE :=true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Display
DEVICE_RESOLUTION := 1280x800
LANDSCAPE_RESOLUTION := 1280x800
PORTRAIT_RESOLUTION := 800x1280
TARGET_PROVIDES_LIBLIGHT := true
#TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
#TW_SECONDARY_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
#TW_MAX_BRIGHTNESS := 255
#TW_DEFAULT_BRIGHTNESS := 120
#TW_DISABLE_DOUBLE_BUFFERING := true
#TW_IGNORE_MAJOR_AXIS_0 := true
#TW_IGNORE_MT_POSITION_0 := true
#TARGET_SCREEN_DENSITY := 160


# Graphics
BOARD_EGL_CFG := $(DEVICE_PATH)/configs/egl.cfg
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
TARGET_USES_ION := true
TARGET_DISPLAY_USE_RETIRE_FENCE := true
EXTENDED_FONT_FOOTPRINT := true

# audio
USE_XML_AUDIO_POLICY_CONF := 1
BOARD_USES_MTK_AUDIO := true
TARGET_OMX_LEGACY_RESCALING := true

#prop
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop
# BOARD_AVB_ENABLE := false

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USES_MKE2FS := true


# Kernel
# TARGET_DEVICE_KERNEL_HEADERS := $(DEVICE_PATH)/kernel-headers
KERNEL_TOOLCHAIN := $(ANDROID_BUILD_TOP)/prebuilts/gcc/$(HOST_OS)-x86/aarch64/aarch64-linux-android-4.9/bin
KERNEL_TOOLCHAIN_PREFIX := aarch64-linux-android-
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x03f88000
BOARD_KERNEL_TAGS_OFFSET := 0x0df88000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
# TARGET_IGNORES_KERNEL_HEADERS := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
TARGET_KERNEL_CONFIG := a04br3_defconfig
TARGET_KERNEL_SOURCE := kernel/sts/a04br3

# Kernel - prebuilt
# TARGET_FORCE_PREBUILT_KERNEL := true
# ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
# TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
# PRODUCT_COPY_FILES += \
#    $(DEVICE_PATH)/prebuilt/kernel:kernel
# endif


# Vendor partition configure
BOARD_USES_VENDORIMAGE := false

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
#TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
RECOVERY_SDCARD_ON_DATA := true
LZMA_RAMDISK_TARGETS := recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/recovery/fstab.mt8167
TARGET_RECOVERY_DEVICE_DIRS += $(DEVICE_PATH)
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Hack: prevent anti rollback
#PLATFORM_SECURITY_PATCH := 2099-12-31
#PLATFORM_VERSION := 16.1.0


# TWRP Configuration
#TW_THEME := landscape_hdpi
#TW_ROTATION := 270
#TW_HWROTATION := 270
#RECOVERY_TOUCHSCREEN_SWAP_Y := true
#RECOVERY_TOUCHSCREEN_FLIP_XY := true
#TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone2/temp
#TW_EXTRA_LANGUAGES := false
#TW_USE_INPUT_EVENTS := true
#TW_INPUT_BLACKLIST := "hbtp_vm"
#TW_SCREEN_BLANK_ON_BOOT := true
# TW_NO_SCREEN_TIMEOUT := true
#TW_USE_TOOLBOX := true
#TW_EXCLUDE_BASH := true
#TW_EXCLUDE_NANO := true
#TW_EXCLUDE_LZMA := false
#TW_EXCLUDE_SED := true
#TW_EXCLUDE_TAR := false
#TW_EXCLUDE_ENCRYPTED_BACKUPS := true
#TW_EXCLUDE_TWRPAPP := true
#TW_EXCLUDE_PYTHON := true
#TW_NO_EXFAT_FUSE := false
#TW_EXCLUDE_MTP := true
#TW_NO_BZIP2 := true
#TW_DEFAULT_LANGUAGE := en
#TW_EXCLUDE_GZIP := false
#TW_EXCLUDE_XZ := true

include vendor/sts/a04br3/BoardConfigVendor.mk

# SELinux
#BOARD_SEPOLICY_DIRS := \
	#$(DEVICE_PATH)/sepolicy/
BOARD_SECCOMP_POLICY += $(DEVICE_PATH)/seccomp_policy
SELINUX_IGNORE_NEVERALLOWS := true
include device/sts/a04br3/remove.mk
