LOCAL_PATH := $(call my-dir)
$(call add-radio-file,logo.img)
$(call add-radio-file,lk.img)
$(call add-radio-file,tee.img)
$(call add-radio-file,preloader.img)
$(call add-radio-file,factory.img)
$(call add-radio-file,twrp.img)
