
#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H
#define BTM_DEF_LOCAL_NAME "TAB-A04-BR3"
#define MAX_ACL_CONNECTIONS 5
#define MAX_L2CAP_CHANNELS 10
#define BTA_DM_SCO_SPDIF_FLAG FALSE
#define AVDT_INSPECT_INCLUDED FALSE
#define BTM_BLE_MAX_MULTI_ADV_INSTANCE 4
#define BLE_INCLUDED         TRUE
#define BTA_GATT_INCLUDED    TRUE
#define SMP_INCLUDED         TRUE
#define BTA_AV_MAX_A2DP_MTU  668
#endif
